import { Box } from "@chakra-ui/react";
import Head from "next/head";
import type { NextPage } from "next";
import SignInBasic from "../src/views/Authentication/SignIn/SignInBasic";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Hello</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box >
        <SignInBasic />
      </Box>
    </>
  );
};

export default Home;
