import { Center } from "@chakra-ui/react";
import Head from "next/head";
import type { NextPage } from "next";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Hello</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Center>
        <h1>Hello</h1>
      </Center>
    </>
  );
};

export default Home;
